export default {
    quick_card_opening: 'Create card',
    cardholder_user: 'Cardholder user',
    card_bin: 'Card BIN',
    number: 'Quantity',
    amount: 'Amount Available',
    submit: 'Create card',
    Please_select_card_bin: 'Please select card bin',
    card_numbers_tips: 'Please fill in the number of cards',
    card_numbers_must_be_greater_than_zero_tips: 'The number of cards must be greater than 0',
    Please_fill_in_the_amount: 'Please fill in the amount',
    amount_must_be_greater_than_twenty_tips: 'The amount must be greater than or equal to 1',
    open_card_tips: 'Open the card, please refresh the list later',
    card_introduce: `
    No AVS verification. No 3DS required.
    Supported channels: Facebook, Google, Amazon, PayPal, Shopify, TikTok, Alibaba, AliExpress, etc.
    Broad support, highly versatile, smooth user experience, and relatively cost-effective.
    All fees generated by this card will be deducted from the wallet balance outside of the card.
    `
}
